title: Efrat Levitan
markdown: kramdown
google_analytics: UA-160733621-1

# for atom feed
author:
  name: Efrat Levitan
  email: efrat890089gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  # - jekyll-feed
  # - jemoji
  - jekyll-twitter-plugin

collections_dir: all_collections
collections:
  posts:
    output: true

paginate: 7
paginate_path: /posts/page:num

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]

